/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../types/enums.js";
import { HTTPClient } from "./http.js";
import { Logger } from "./logger.js";
import { RetryConfig } from "./retries.js";
import { Params, pathToFunc } from "./url.js";

/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = [
  /**
   * Configurable environment
   */
  "{scheme}://{host}",
] as const;

export const ServerScheme = {
  Http: "http",
  Https: "https",
} as const;
export type ServerScheme = ClosedEnum<typeof ServerScheme>;

export const ServerHost = {
  IdDevApiFluidapiIo: "id.dev.api.fluidapi.io",
  IdApiFluidapiIo: "id.api.fluidapi.io",
  Localhost9999: "localhost:9999",
} as const;
export type ServerHost = ClosedEnum<typeof ServerHost>;

export type SDKOptions = {
  bearerAuth?: string | (() => Promise<string>) | undefined;

  httpClient?: HTTPClient;
  /**
   * Allows overriding the default server used by the SDK
   */
  serverIdx?: number | undefined;
  /**
   * Sets the scheme variable for url substitution
   */
  scheme?: ServerScheme | undefined;
  /**
   * Sets the host variable for url substitution
   */
  host?: ServerHost | undefined;
  /**
   * Allows overriding the default server URL used by the SDK
   */
  serverURL?: string | undefined;
  /**
   * Allows overriding the default user agent used by the SDK
   */
  userAgent?: string | undefined;
  /**
   * Allows overriding the default retry config used by the SDK
   */
  retryConfig?: RetryConfig;
  timeoutMs?: number;
  debugLogger?: Logger;
};

export function serverURLFromOptions(options: SDKOptions): URL | null {
  let serverURL = options.serverURL;

  const serverParams: Params[] = [
    {
      "scheme": options.scheme ?? "https",
      "host": options.host ?? "id.dev.api.fluidapi.io",
    },
  ];
  let params: Params = {};

  if (!serverURL) {
    const serverIdx = options.serverIdx ?? 0;
    if (serverIdx < 0 || serverIdx >= ServerList.length) {
      throw new Error(`Invalid server index ${serverIdx}`);
    }
    serverURL = ServerList[serverIdx] || "";
    params = serverParams[serverIdx] || {};
  }

  const u = pathToFunc(serverURL)(params);
  return new URL(u);
}

export const SDK_METADATA = {
  language: "typescript",
  openapiDocVersion: "0.1.0",
  sdkVersion: "0.4.1",
  genVersion: "2.869.3",
  userAgent: "speakeasy-sdk/typescript 0.4.1 2.869.3 0.1.0 fluidapi",
} as const;
