/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { SDKError } from "./sdk-error.js";

/**
 * Invalid request parameters
 */
export type OAuth2ErrorResponseData = {
  /**
   * OAuth2 error code (RFC 6749)
   */
  error: string;
  /**
   * Human-readable error description
   */
  errorDescription?: string | undefined;
};

/**
 * Invalid request parameters
 */
export class OAuth2ErrorResponse extends SDKError {
  /**
   * OAuth2 error code (RFC 6749)
   */
  error: string;
  /**
   * Human-readable error description
   */
  errorDescription?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: OAuth2ErrorResponseData;

  constructor(
    err: OAuth2ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.errorDescription != null) {
      this.errorDescription = err.errorDescription;
    }

    this.name = "OAuth2ErrorResponse";
  }
}

/** @internal */
export const OAuth2ErrorResponse$inboundSchema: z.ZodMiniType<
  OAuth2ErrorResponse,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    error_description: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "error_description": "errorDescription",
    });

    return new OAuth2ErrorResponse(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
