/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { activationsActivateFlowkit } from "../funcs/activations-activate-flowkit.js";
import { activationsDeleteFlowkitActivation } from "../funcs/activations-delete-flowkit-activation.js";
import { activationsListFlowkitActivations } from "../funcs/activations-list-flowkit-activations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Activations extends ClientSDK {
  /**
   * List activated flowkits
   *
   * @remarks
   * Returns all flowkit activations for the authenticated tenant.
   */
  async listFlowkitActivations(
    request: operations.ListFlowkitActivationsRequest,
    options?: RequestOptions,
  ): Promise<models.FlowkitActivationListResponse> {
    return unwrapAsync(activationsListFlowkitActivations(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a flowkit activation
   *
   * @remarks
   * Removes an active flowkit instance for the authenticated tenant.
   *
   * The activation to be removed is identified by query parameters.
   */
  async deleteFlowkitActivation(
    request: operations.DeleteFlowkitActivationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(activationsDeleteFlowkitActivation(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate a flowkit integration
   *
   * @remarks
   * Activates a flowkit for the given tenant and integration, supplying
   * connector credentials and per-tenant runtime data.
   *
   * The `key` query parameter identifies the flowkit definition to activate.
   */
  async activateFlowkit(
    request: operations.ActivateFlowkitRequest,
    options?: RequestOptions,
  ): Promise<models.FlowkitActivationRecord> {
    return unwrapAsync(activationsActivateFlowkit(
      this,
      request,
      options,
    ));
  }
}
