/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { flowkitsActivateFlowkit } from "../funcs/flowkits-activate-flowkit.js";
import { flowkitsDeleteFlowkitActivation } from "../funcs/flowkits-delete-flowkit-activation.js";
import { flowkitsListFlowkitActivations } from "../funcs/flowkits-list-flowkit-activations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Flowkits extends ClientSDK {
  /**
   * Activate Flowkit
   *
   * @remarks
   * Activates a Flowkit for the Conta Azul integration using the provided
   * connector credentials and tenant/user context metadata.
   */
  async activateFlowkit(
    request: operations.ActivateFlowkitRequest,
    options?: RequestOptions,
  ): Promise<models.FlowkitActivation> {
    return unwrapAsync(flowkitsActivateFlowkit(
      this,
      request,
      options,
    ));
  }

  /**
   * List active Flowkits
   *
   * @remarks
   * Returns the currently activated Flowkits.
   *
   * This operation is currently documented with a mock response so the SDK
   * can be generated and consumed by the client team before the final API
   * contract is available.
   */
  async listFlowkitActivations(
    options?: RequestOptions,
  ): Promise<models.ListFlowkitActivationsResponse> {
    return unwrapAsync(flowkitsListFlowkitActivations(
      this,
      options,
    ));
  }

  /**
   * Delete Flowkit activation
   *
   * @remarks
   * Deletes an activated Flowkit by its activation identifier.
   *
   * This operation is currently scaffolded for SDK generation and uses a
   * mock success response.
   */
  async deleteFlowkitActivation(
    request: operations.DeleteFlowkitActivationRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteFlowkitActivationResponse> {
    return unwrapAsync(flowkitsDeleteFlowkitActivation(
      this,
      request,
      options,
    ));
  }
}
