/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { flowkitsListFlowkits } from "../funcs/flowkits-list-flowkits.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Flowkits extends ClientSDK {
  /**
   * List available flowkits
   *
   * @remarks
   * Returns the catalog of flowkit definitions available to the authenticated tenant.
   *
   * > **Status**: endpoint reservado — documentação detalhada pendente.
   */
  async listFlowkits(
    request: operations.ListFlowkitsRequest,
    options?: RequestOptions,
  ): Promise<models.FlowkitListResponse> {
    return unwrapAsync(flowkitsListFlowkits(
      this,
      request,
      options,
    ));
  }
}
