/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataGetJwks } from "../funcs/metadata-get-jwks.js";
import { metadataHealthCheck } from "../funcs/metadata-health-check.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Metadata extends ClientSDK {
  /**
   * Health check
   */
  async healthCheck(
    options?: RequestOptions,
  ): Promise<models.HealthResponse> {
    return unwrapAsync(metadataHealthCheck(
      this,
      options,
    ));
  }

  /**
   * Get public signing keys
   *
   * @remarks
   * Returns the JWKS used to validate Fluid-signed JWTs.
   */
  async getJwks(
    options?: RequestOptions,
  ): Promise<models.JWKSet> {
    return unwrapAsync(metadataGetJwks(
      this,
      options,
    ));
  }
}
