/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Activations } from "./activations.js";
import { Flowkits } from "./flowkits.js";
import { Metadata } from "./metadata.js";
import { Session } from "./session.js";
import { Tokens } from "./tokens.js";

export class Fluidapi extends ClientSDK {
  private _metadata?: Metadata;
  get metadata(): Metadata {
    return (this._metadata ??= new Metadata(this._options));
  }

  private _tokens?: Tokens;
  get tokens(): Tokens {
    return (this._tokens ??= new Tokens(this._options));
  }

  private _session?: Session;
  get session(): Session {
    return (this._session ??= new Session(this._options));
  }

  private _flowkits?: Flowkits;
  get flowkits(): Flowkits {
    return (this._flowkits ??= new Flowkits(this._options));
  }

  private _activations?: Activations;
  get activations(): Activations {
    return (this._activations ??= new Activations(this._options));
  }
}
