/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Metadata } from "./metadata.js";
import { Session } from "./session.js";
import { Tokens } from "./tokens.js";

export class SDK extends ClientSDK {
  private _metadata?: Metadata;
  get metadata(): Metadata {
    return (this._metadata ??= new Metadata(this._options));
  }

  private _tokens?: Tokens;
  get tokens(): Tokens {
    return (this._tokens ??= new Tokens(this._options));
  }

  private _session?: Session;
  get session(): Session {
    return (this._session ??= new Session(this._options));
  }
}
