/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionExchangeBootstrapToken } from "../funcs/session-exchange-bootstrap-token.js";
import { sessionRefreshUserSession } from "../funcs/session-refresh-user-session.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Session extends ClientSDK {
  /**
   * Exchange bootstrap token for user session
   *
   * @remarks
   * Exchanges the short-lived bootstrap JWT issued by `POST /users/token` for a
   * Hydra-managed session token pair (`access_token` + `refresh_token`).
   *
   * The bootstrap token is **single-use**: a second call with the same token
   * returns `401 invalid_grant`. Claims from the bootstrap token (workspace_id,
   * tenant_id, user_id, etc.) are forwarded into the Hydra session via the
   * server-side authorization code flow.
   *
   * The resulting `refresh_token` can be renewed via `POST /users/token/refresh`.
   */
  async exchangeBootstrapToken(
    request: models.ExchangeRequest,
    options?: RequestOptions,
  ): Promise<models.SessionTokenData> {
    return unwrapAsync(sessionExchangeBootstrapToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Renew user session (refresh token)
   *
   * @remarks
   * Exchanges a Hydra refresh token for a new session token pair
   * (`access_token` + `refresh_token`).
   *
   * The `fluid-user-session` client credentials are handled server-side.
   * Browsers and mobile clients must **not** hold or send the client secret —
   * only the `refresh_token` is required.
   */
  async refreshUserSession(
    request: models.RefreshRequest,
    options?: RequestOptions,
  ): Promise<models.SessionTokenData> {
    return unwrapAsync(sessionRefreshUserSession(
      this,
      request,
      options,
    ));
  }
}
