/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokensIssueFluidTokenLegacy } from "../funcs/tokens-issue-fluid-token-legacy.js";
import { tokensIssueUser } from "../funcs/tokens-issue-user.js";
import { tokensIssue } from "../funcs/tokens-issue.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tokens extends ClientSDK {
  /**
   * Issue M2M token (client_credentials)
   *
   * @remarks
   * OAuth2 token endpoint for M2M (machine-to-machine) access.
   * Only `grant_type=client_credentials` is supported.
   *
   * Performs a `client_credentials` grant against the Authorization Server and
   * returns a Hydra-issued access token (JWT) following RFC 6749 token response format.
   *
   * The OAuth2 client must be registered first via
   * `POST /v1/tenants/{tenant_id}/credentials`.
   *
   * By default the token is issued with all scopes configured for the tenant.
   * You can request a subset by passing `scope`. Requesting a scope not in the
   * tenant's allowlist returns `400 invalid_scope`.
   *
   * > **User session refresh:** use `POST /users/token/refresh` instead.
   * > The client secret is handled server-side and must not be sent by browsers.
   */
  async issue(
    request: models.ClientCredentialsRequest,
    options?: RequestOptions,
  ): Promise<models.TokenData> {
    return unwrapAsync(tokensIssue(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue Fluid-signed M2M token (legacy)
   *
   * @remarks
   * **Deprecated** — prefer `POST /oauth2/token` with `grant_type=client_credentials`.
   *
   * Validates client credentials against the Authorization Server and generates
   * a JWT signed by Fluid carrying `workspace_id`, `tenant_id`, `client_id`, and
   * `credential_type` claims.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async issueFluidTokenLegacy(
    request: models.ClientCredentialsRequest,
    options?: RequestOptions,
  ): Promise<models.TokenData> {
    return unwrapAsync(tokensIssueFluidTokenLegacy(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue bootstrap token for end user
   *
   * @remarks
   * Issues a short-lived bootstrap JWT for an end user (workspace or customer scope).
   *
   * The token lifetime is capped at `BOOTSTRAP_TOKEN_TTL_SECONDS` (default: 300s)
   * regardless of the `expires_in` value in the request. This token is single-use
   * and is intended to be exchanged immediately via `POST /users/token/exchange`.
   *
   * Supported authentication modes:
   * - `Authorization: Bearer <m2m_token>` — preferred. The token must be a
   *   Fluid-signed M2M JWT with `scope` including `fluid:api`.
   *   Canonical first-access provisioning is only available in this mode.
   * - HTTP Basic Auth with `client_id` + `client_secret`.
   *   Provisioning is skipped in this mode.
   *
   * If `customer_external_id` is present, the JWT is issued with `scope: customer`.
   * Otherwise it is issued with `scope: workspace`.
   */
  async issueUser(
    security: operations.IssueUserTokenSecurity,
    request: models.UserTokenRequest,
    options?: RequestOptions,
  ): Promise<models.UserTokenData> {
    return unwrapAsync(tokensIssueUser(
      this,
      security,
      request,
      options,
    ));
  }
}
