/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokensIssueFluidToken } from "../funcs/tokens-issue-fluid-token.js";
import { tokensIssueToken } from "../funcs/tokens-issue-token.js";
import { tokensIssueUserToken } from "../funcs/tokens-issue-user-token.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tokens extends ClientSDK {
  /**
   * Issue access token (client_credentials)
   *
   * @remarks
   * Standard OAuth2 token endpoint. Performs a `client_credentials` grant
   * against the Authorization Server and returns the access token (JWT).
   *
   * The OAuth2 client must be registered first via
   * `POST /v1/tenants/{tenant_id}/credentials`.
   *
   * ### Scope reduction
   *
   * By default the token is issued with all scopes configured for the tenant.
   * You can request a subset by passing `scope` in the form body.
   * Requesting a scope not in the tenant's allowlist returns `400 invalid_scope`.
   *
   * **Available scopes:** `fluid:api`
   */
  async issueToken(
    request: models.IssueTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.IssueTokenResponse> {
    return unwrapAsync(tokensIssueToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue Fluid-signed M2M token
   *
   * @remarks
   * Validates client credentials against the Authorization Server and then
   * generates a JWT signed by Fluid.
   *
   * This endpoint coexists with `/oauth2/token`.
   * Use `/oauth2/token` when you want the standard Hydra-backed token flow.
   * Use `/oauth2/token-fluid` when you need a Fluid-signed JWT carrying
   * `workspace_id`, `tenant_id`, `client_id`, and `credential_type` claims for M2M calls.
   */
  async issueFluidToken(
    request: models.IssueTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.IssueFluidTokenResponse> {
    return unwrapAsync(tokensIssueFluidToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue end-user token
   *
   * @remarks
   * Issues a JWT for an end user (workspace user or customer user).
   *
   * Supported authentication modes:
   * - `Authorization: Bearer <m2m_token>` — preferred. The token must be a
   *   Fluid-signed M2M JWT with `scope` including `fluid:api`.
   *   Canonical first-access provisioning via external lookup/create is only
   *   available in this mode.
   * - HTTP Basic Auth with `client_id` + `client_secret`.
   *   In this mode the service does not perform canonical lookup/create.
   *
   * If `customer_external_id` is present, the JWT is issued with `scope: customer`.
   * Otherwise it is issued with `scope: workspace`.
   *
   * When canonical first-access provisioning is enabled, `email` is required
   * so the service can lookup or create the canonical user before issuing the token.
   *
   * When canonical provisioning is disabled by server configuration, the
   * service may materialize local IAM context by assuming `external_id` is
   * already the canonical `user_id`.
   */
  async issueUserToken(
    request: models.UserTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.IssueUserTokenResponse> {
    return unwrapAsync(tokensIssueUserToken(
      this,
      request,
      options,
    ));
  }
}
