/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the fluidapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx metadataHealthCheck.example.ts
 */

import { Fluidapi } from "fluidapi";

const fluidapi = new Fluidapi({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await fluidapi.metadata.healthCheck();

  console.log(result);
}

main().catch(console.error);
