/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the openapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx metadataHealthCheck.example.ts
 */

import { SDK } from "openapi";

const sdk = new SDK({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await sdk.metadata.healthCheck();

  console.log(result);
}

main().catch(console.error);
