workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  auth:
    inputs:
      - location: ../public.yaml
    registry:
      location: registry.speakeasyapi.dev/fluid/iam-sjd/auth
targets:
  fluidapi:
    target: typescript
    source: auth
    publish:
      npm:
        token: $npm_token
