/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ActivateFlowkitRequest = {
  /**
   * Tenant slug (e.g. `contaazul`).
   */
  tenant: string;
  /**
   * Integration identifier (e.g. `tray`, `contaazulprivado`).
   */
  integration: string;
  /**
   * Flowkit definition key (UUID).
   */
  key: string;
  body: models.ActivateFlowkitRequest;
};

/** @internal */
export type ActivateFlowkitRequest$Outbound = {
  tenant: string;
  integration: string;
  key: string;
  body: models.ActivateFlowkitRequest$Outbound;
};

/** @internal */
export const ActivateFlowkitRequest$outboundSchema: z.ZodMiniType<
  ActivateFlowkitRequest$Outbound,
  ActivateFlowkitRequest
> = z.object({
  tenant: z.string(),
  integration: z.string(),
  key: z.string(),
  body: models.ActivateFlowkitRequest$outboundSchema,
});

export function activateFlowkitRequestToJSON(
  activateFlowkitRequest: ActivateFlowkitRequest,
): string {
  return JSON.stringify(
    ActivateFlowkitRequest$outboundSchema.parse(activateFlowkitRequest),
  );
}
