/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ActivateFlowkitRequest = {
  /**
   * Activation key used to authorize the Flowkit activation.
   */
  key: string;
  body: models.ActivateFlowkitRequest;
};

/** @internal */
export type ActivateFlowkitRequest$Outbound = {
  key: string;
  body: models.ActivateFlowkitRequest$Outbound;
};

/** @internal */
export const ActivateFlowkitRequest$outboundSchema: z.ZodMiniType<
  ActivateFlowkitRequest$Outbound,
  ActivateFlowkitRequest
> = z.object({
  key: z.string(),
  body: models.ActivateFlowkitRequest$outboundSchema,
});

export function activateFlowkitRequestToJSON(
  activateFlowkitRequest: ActivateFlowkitRequest,
): string {
  return JSON.stringify(
    ActivateFlowkitRequest$outboundSchema.parse(activateFlowkitRequest),
  );
}
