/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteFlowkitActivationRequest = {
  /**
   * Identifier of the activated Flowkit to delete.
   */
  activationId: string;
};

/** @internal */
export type DeleteFlowkitActivationRequest$Outbound = {
  activationId: string;
};

/** @internal */
export const DeleteFlowkitActivationRequest$outboundSchema: z.ZodMiniType<
  DeleteFlowkitActivationRequest$Outbound,
  DeleteFlowkitActivationRequest
> = z.object({
  activationId: z.string(),
});

export function deleteFlowkitActivationRequestToJSON(
  deleteFlowkitActivationRequest: DeleteFlowkitActivationRequest,
): string {
  return JSON.stringify(
    DeleteFlowkitActivationRequest$outboundSchema.parse(
      deleteFlowkitActivationRequest,
    ),
  );
}
