/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteFlowkitActivationRequest = {
  /**
   * Tenant slug (e.g. `contaazul`).
   */
  tenant: string;
  /**
   * Activation ID to delete (e.g. `bling-linx-1.0.7`).
   */
  id: string;
};

/** @internal */
export type DeleteFlowkitActivationRequest$Outbound = {
  tenant: string;
  id: string;
};

/** @internal */
export const DeleteFlowkitActivationRequest$outboundSchema: z.ZodMiniType<
  DeleteFlowkitActivationRequest$Outbound,
  DeleteFlowkitActivationRequest
> = z.object({
  tenant: z.string(),
  id: z.string(),
});

export function deleteFlowkitActivationRequestToJSON(
  deleteFlowkitActivationRequest: DeleteFlowkitActivationRequest,
): string {
  return JSON.stringify(
    DeleteFlowkitActivationRequest$outboundSchema.parse(
      deleteFlowkitActivationRequest,
    ),
  );
}
