/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type IssueUserTokenSecurity = {
  bearerAuth?: string | undefined;
  basicAuth?: models.SchemeBasicAuth | undefined;
};

/** @internal */
export type IssueUserTokenSecurity$Outbound = {
  BearerAuth?: string | undefined;
  BasicAuth?: models.SchemeBasicAuth$Outbound | undefined;
};

/** @internal */
export const IssueUserTokenSecurity$outboundSchema: z.ZodMiniType<
  IssueUserTokenSecurity$Outbound,
  IssueUserTokenSecurity
> = z.pipe(
  z.object({
    bearerAuth: z.optional(z.string()),
    basicAuth: z.optional(models.SchemeBasicAuth$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      bearerAuth: "BearerAuth",
      basicAuth: "BasicAuth",
    });
  }),
);

export function issueUserTokenSecurityToJSON(
  issueUserTokenSecurity: IssueUserTokenSecurity,
): string {
  return JSON.stringify(
    IssueUserTokenSecurity$outboundSchema.parse(issueUserTokenSecurity),
  );
}
