/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Fluid-signed M2M token issued
 */
export type IssueFluidTokenResponse = {
  ok: boolean;
  data?: models.TokenData | undefined;
};

/** @internal */
export const IssueFluidTokenResponse$inboundSchema: z.ZodMiniType<
  IssueFluidTokenResponse,
  unknown
> = z.object({
  ok: types.boolean(),
  data: types.optional(models.TokenData$inboundSchema),
});

export function issueFluidTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<IssueFluidTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IssueFluidTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IssueFluidTokenResponse' from JSON`,
  );
}
