/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * User token issued
 */
export type IssueUserTokenResponse = {
  ok: boolean;
  data?: models.UserTokenData | undefined;
};

/** @internal */
export const IssueUserTokenResponse$inboundSchema: z.ZodMiniType<
  IssueUserTokenResponse,
  unknown
> = z.object({
  ok: types.boolean(),
  data: types.optional(models.UserTokenData$inboundSchema),
});

export function issueUserTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<IssueUserTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IssueUserTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IssueUserTokenResponse' from JSON`,
  );
}
