/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListFlowkitsRequest = {
  /**
   * Tenant slug (e.g. `contaazul`).
   */
  tenant: string;
  page?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export type ListFlowkitsRequest$Outbound = {
  tenant: string;
  page: number;
  limit: number;
};

/** @internal */
export const ListFlowkitsRequest$outboundSchema: z.ZodMiniType<
  ListFlowkitsRequest$Outbound,
  ListFlowkitsRequest
> = z.object({
  tenant: z.string(),
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 20),
});

export function listFlowkitsRequestToJSON(
  listFlowkitsRequest: ListFlowkitsRequest,
): string {
  return JSON.stringify(
    ListFlowkitsRequest$outboundSchema.parse(listFlowkitsRequest),
  );
}
