/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListFlowkitActivationsRequest = {
  /**
   * Tenant slug (e.g. `contaazul`).
   */
  tenant: string;
  page?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export type ListFlowkitActivationsRequest$Outbound = {
  tenant: string;
  page: number;
  limit: number;
};

/** @internal */
export const ListFlowkitActivationsRequest$outboundSchema: z.ZodMiniType<
  ListFlowkitActivationsRequest$Outbound,
  ListFlowkitActivationsRequest
> = z.object({
  tenant: z.string(),
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 20),
});

export function listFlowkitActivationsRequestToJSON(
  listFlowkitActivationsRequest: ListFlowkitActivationsRequest,
): string {
  return JSON.stringify(
    ListFlowkitActivationsRequest$outboundSchema.parse(
      listFlowkitActivationsRequest,
    ),
  );
}
