/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  FlowkitActivationContext,
  FlowkitActivationContext$Outbound,
  FlowkitActivationContext$outboundSchema,
} from "./flowkit-activation-context.js";
import {
  FlowkitCredentials,
  FlowkitCredentials$Outbound,
  FlowkitCredentials$outboundSchema,
} from "./flowkit-credentials.js";

export type ActivateFlowkitRequest = {
  credentials: FlowkitCredentials;
  data: FlowkitActivationContext;
};

/** @internal */
export type ActivateFlowkitRequest$Outbound = {
  credentials: FlowkitCredentials$Outbound;
  data: FlowkitActivationContext$Outbound;
};

/** @internal */
export const ActivateFlowkitRequest$outboundSchema: z.ZodMiniType<
  ActivateFlowkitRequest$Outbound,
  ActivateFlowkitRequest
> = z.object({
  credentials: FlowkitCredentials$outboundSchema,
  data: FlowkitActivationContext$outboundSchema,
});

export function activateFlowkitRequestToJSON(
  activateFlowkitRequest: ActivateFlowkitRequest,
): string {
  return JSON.stringify(
    ActivateFlowkitRequest$outboundSchema.parse(activateFlowkitRequest),
  );
}
