/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AuditEntryByName,
  AuditEntryByName$inboundSchema,
} from "./audit-entry-by-name.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuditByName = {
  /**
   * Audit entry carrying first_name / last_name (list responses).
   */
  created?: AuditEntryByName | undefined;
  /**
   * Audit entry carrying first_name / last_name (list responses).
   */
  updated?: AuditEntryByName | undefined;
};

/** @internal */
export const AuditByName$inboundSchema: z.ZodMiniType<AuditByName, unknown> = z
  .object({
    created: types.optional(AuditEntryByName$inboundSchema),
    updated: types.optional(AuditEntryByName$inboundSchema),
  });

export function auditByNameFromJSON(
  jsonString: string,
): SafeParseResult<AuditByName, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditByName$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditByName' from JSON`,
  );
}
