/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Audit entry carrying a user_id (activation response).
 */
export type AuditEntryById = {
  timestamp?: Date | undefined;
  userId?: string | undefined;
};

/** @internal */
export const AuditEntryById$inboundSchema: z.ZodMiniType<
  AuditEntryById,
  unknown
> = z.pipe(
  z.object({
    timestamp: types.optional(types.date()),
    user_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "user_id": "userId",
    });
  }),
);

export function auditEntryByIdFromJSON(
  jsonString: string,
): SafeParseResult<AuditEntryById, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEntryById$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEntryById' from JSON`,
  );
}
