/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { AuditEntry, AuditEntry$inboundSchema } from "./audit-entry.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuditMetadata = {
  created: AuditEntry;
  updateHistory: Array<AuditEntry>;
  updated: AuditEntry;
};

/** @internal */
export const AuditMetadata$inboundSchema: z.ZodMiniType<
  AuditMetadata,
  unknown
> = z.pipe(
  z.object({
    created: AuditEntry$inboundSchema,
    update_history: z.array(AuditEntry$inboundSchema),
    updated: AuditEntry$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "update_history": "updateHistory",
    });
  }),
);

export function auditMetadataFromJSON(
  jsonString: string,
): SafeParseResult<AuditMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditMetadata' from JSON`,
  );
}
