/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Audit entry carrying first_name / last_name (list responses).
 */
export type AuditEntryByName = {
  firstName?: string | undefined;
  lastName?: string | undefined;
  timestamp?: Date | undefined;
};

/** @internal */
export const AuditEntryByName$inboundSchema: z.ZodMiniType<
  AuditEntryByName,
  unknown
> = z.pipe(
  z.object({
    first_name: types.optional(types.string()),
    last_name: types.optional(types.string()),
    timestamp: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "first_name": "firstName",
      "last_name": "lastName",
    });
  }),
);

export function auditEntryByNameFromJSON(
  jsonString: string,
): SafeParseResult<AuditEntryByName, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEntryByName$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEntryByName' from JSON`,
  );
}
