/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuditEntry = {
  timestamp: Date;
  userId: string;
};

/** @internal */
export const AuditEntry$inboundSchema: z.ZodMiniType<AuditEntry, unknown> = z
  .pipe(
    z.object({
      timestamp: types.date(),
      user_id: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "user_id": "userId",
      });
    }),
  );

export function auditEntryFromJSON(
  jsonString: string,
): SafeParseResult<AuditEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEntry' from JSON`,
  );
}
