/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AuditEntryById,
  AuditEntryById$inboundSchema,
} from "./audit-entry-by-id.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuditById = {
  /**
   * Audit entry carrying a user_id (activation response).
   */
  created?: AuditEntryById | undefined;
  /**
   * Audit entry carrying a user_id (activation response).
   */
  updated?: AuditEntryById | undefined;
  updateHistory?: Array<AuditEntryById> | undefined;
};

/** @internal */
export const AuditById$inboundSchema: z.ZodMiniType<AuditById, unknown> = z
  .pipe(
    z.object({
      created: types.optional(AuditEntryById$inboundSchema),
      updated: types.optional(AuditEntryById$inboundSchema),
      update_history: types.optional(z.array(AuditEntryById$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "update_history": "updateHistory",
      });
    }),
  );

export function auditByIdFromJSON(
  jsonString: string,
): SafeParseResult<AuditById, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditById$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditById' from JSON`,
  );
}
