/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Data = {
  deleted: boolean;
  id: string;
};

export type DeleteFlowkitActivationResponse = {
  data: Data;
};

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.object({
  deleted: types.boolean(),
  id: types.string(),
});

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const DeleteFlowkitActivationResponse$inboundSchema: z.ZodMiniType<
  DeleteFlowkitActivationResponse,
  unknown
> = z.object({
  data: z.lazy(() => Data$inboundSchema),
});

export function deleteFlowkitActivationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteFlowkitActivationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteFlowkitActivationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteFlowkitActivationResponse' from JSON`,
  );
}
