/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ErrorT = {
  /**
   * Machine-readable error code
   */
  code: string;
  /**
   * Human-readable description
   */
  message: string;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  code: types.string(),
  message: types.string(),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}
