/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ExchangeRequest = {
  /**
   * Bootstrap JWT issued by `POST /users/token`
   */
  token: string;
};

/** @internal */
export type ExchangeRequest$Outbound = {
  token: string;
};

/** @internal */
export const ExchangeRequest$outboundSchema: z.ZodMiniType<
  ExchangeRequest$Outbound,
  ExchangeRequest
> = z.object({
  token: z.string(),
});

export function exchangeRequestToJSON(
  exchangeRequest: ExchangeRequest,
): string {
  return JSON.stringify(ExchangeRequest$outboundSchema.parse(exchangeRequest));
}
