/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitActivatedItem,
  FlowkitActivatedItem$inboundSchema,
} from "./flowkit-activated-item.js";
import { Meta, Meta$inboundSchema } from "./meta.js";

export type FlowkitActivationListResponseData = {
  data?: Array<FlowkitActivatedItem> | undefined;
  total?: Meta | undefined;
};

export type FlowkitActivationListResponse = {
  data?: FlowkitActivationListResponseData | undefined;
};

/** @internal */
export const FlowkitActivationListResponseData$inboundSchema: z.ZodMiniType<
  FlowkitActivationListResponseData,
  unknown
> = z.object({
  data: types.optional(z.array(FlowkitActivatedItem$inboundSchema)),
  total: types.optional(Meta$inboundSchema),
});

export function flowkitActivationListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitActivationListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitActivationListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitActivationListResponseData' from JSON`,
  );
}

/** @internal */
export const FlowkitActivationListResponse$inboundSchema: z.ZodMiniType<
  FlowkitActivationListResponse,
  unknown
> = z.object({
  data: types.optional(
    z.lazy(() => FlowkitActivationListResponseData$inboundSchema),
  ),
});

export function flowkitActivationListResponseFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitActivationListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitActivationListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitActivationListResponse' from JSON`,
  );
}
