/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitActivatedItem,
  FlowkitActivatedItem$inboundSchema,
} from "./flowkit-activated-item.js";
import { MetaCount, MetaCount$inboundSchema } from "./meta-count.js";

export type FlowkitActivationListEnvelope = {
  data: Array<FlowkitActivatedItem>;
  total: MetaCount;
};

/** @internal */
export const FlowkitActivationListEnvelope$inboundSchema: z.ZodMiniType<
  FlowkitActivationListEnvelope,
  unknown
> = z.object({
  data: z.array(FlowkitActivatedItem$inboundSchema),
  total: MetaCount$inboundSchema,
});

export function flowkitActivationListEnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitActivationListEnvelope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitActivationListEnvelope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitActivationListEnvelope' from JSON`,
  );
}
