/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AuditById, AuditById$inboundSchema } from "./audit-by-id.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const FlowkitActivationRecordStatus = {
  InProgress: "in_progress",
  Active: "active",
  Error: "error",
  Cancelled: "cancelled",
} as const;
export type FlowkitActivationRecordStatus = OpenEnum<
  typeof FlowkitActivationRecordStatus
>;

/**
 * Activation record returned after a successful POST activate.
 */
export type FlowkitActivationRecord = {
  id?: string | undefined;
  flowkitName?: string | undefined;
  flowkitRevision?: string | undefined;
  description?: string | undefined;
  identifier?: string | undefined;
  published?: boolean | undefined;
  status?: FlowkitActivationRecordStatus | undefined;
  connectors?: Array<string> | undefined;
  audit?: AuditById | undefined;
};

/** @internal */
export const FlowkitActivationRecordStatus$inboundSchema: z.ZodMiniType<
  FlowkitActivationRecordStatus,
  unknown
> = openEnums.inboundSchema(FlowkitActivationRecordStatus);

/** @internal */
export const FlowkitActivationRecord$inboundSchema: z.ZodMiniType<
  FlowkitActivationRecord,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    flowkit_name: types.optional(types.string()),
    flowkit_revision: types.optional(types.string()),
    description: types.optional(types.string()),
    identifier: types.optional(types.string()),
    published: types.optional(types.boolean()),
    status: types.optional(FlowkitActivationRecordStatus$inboundSchema),
    connectors: types.optional(z.array(types.string())),
    audit: types.optional(AuditById$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "flowkit_name": "flowkitName",
      "flowkit_revision": "flowkitRevision",
    });
  }),
);

export function flowkitActivationRecordFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitActivationRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitActivationRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitActivationRecord' from JSON`,
  );
}
