/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AuditMetadata,
  AuditMetadata$inboundSchema,
} from "./audit-metadata.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FlowkitActivation = {
  audit: AuditMetadata;
  connectors: Array<string>;
  description: string;
  flowkitName: string;
  flowkitRevision: string;
  id: string;
  identifier: string;
  published: boolean;
  status: string;
};

/** @internal */
export const FlowkitActivation$inboundSchema: z.ZodMiniType<
  FlowkitActivation,
  unknown
> = z.pipe(
  z.object({
    audit: AuditMetadata$inboundSchema,
    connectors: z.array(types.string()),
    description: types.string(),
    flowkit_name: types.string(),
    flowkit_revision: types.string(),
    id: types.string(),
    identifier: types.string(),
    published: types.boolean(),
    status: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "flowkit_name": "flowkitName",
      "flowkit_revision": "flowkitRevision",
    });
  }),
);

export function flowkitActivationFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitActivation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitActivation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitActivation' from JSON`,
  );
}
