/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitUserAudit,
  FlowkitUserAudit$inboundSchema,
} from "./flowkit-user-audit.js";

export type FlowkitActivatedItem = {
  typename: string;
  activations: number;
  audit: FlowkitUserAudit;
  connectors: Array<string>;
  flowkitName: string;
  flowkitRevision: string;
  flows: number;
  id: string;
  identifier: string;
  status: string;
};

/** @internal */
export const FlowkitActivatedItem$inboundSchema: z.ZodMiniType<
  FlowkitActivatedItem,
  unknown
> = z.pipe(
  z.object({
    __typename: types.string(),
    activations: types.number(),
    audit: FlowkitUserAudit$inboundSchema,
    connectors: z.array(types.string()),
    flowkit_name: types.string(),
    flowkit_revision: types.string(),
    flows: types.number(),
    id: types.string(),
    identifier: types.string(),
    status: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "__typename": "typename",
      "flowkit_name": "flowkitName",
      "flowkit_revision": "flowkitRevision",
    });
  }),
);

export function flowkitActivatedItemFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitActivatedItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitActivatedItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitActivatedItem' from JSON`,
  );
}
