/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FlowkitFlowRef = {
  flowRevision?: number | undefined;
};

/** @internal */
export const FlowkitFlowRef$inboundSchema: z.ZodMiniType<
  FlowkitFlowRef,
  unknown
> = z.pipe(
  z.object({
    flow_revision: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "flow_revision": "flowRevision",
    });
  }),
);

export function flowkitFlowRefFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitFlowRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitFlowRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitFlowRef' from JSON`,
  );
}
