/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type FlowkitActivationContext = {
  /**
   * Client-side identifier for the activated Flowkit.
   */
  identifier: string;
  /**
   * Tenant identifier propagated to the integration context.
   */
  xTenantId: string;
  /**
   * User identifier propagated to the integration context.
   */
  xUserId: string;
  /**
   * User email propagated to the integration context.
   */
  xEmail: string;
};

/** @internal */
export type FlowkitActivationContext$Outbound = {
  identifier: string;
  "x-tenantId": string;
  "x-userId": string;
  "x-email": string;
};

/** @internal */
export const FlowkitActivationContext$outboundSchema: z.ZodMiniType<
  FlowkitActivationContext$Outbound,
  FlowkitActivationContext
> = z.pipe(
  z.object({
    identifier: z.string(),
    xTenantId: z.string(),
    xUserId: z.string(),
    xEmail: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      xTenantId: "x-tenantId",
      xUserId: "x-userId",
      xEmail: "x-email",
    });
  }),
);

export function flowkitActivationContextToJSON(
  flowkitActivationContext: FlowkitActivationContext,
): string {
  return JSON.stringify(
    FlowkitActivationContext$outboundSchema.parse(flowkitActivationContext),
  );
}
