/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FlowkitUserAuditEntry = {
  firstName: string;
  lastName: string;
  timestamp: Date;
};

/** @internal */
export const FlowkitUserAuditEntry$inboundSchema: z.ZodMiniType<
  FlowkitUserAuditEntry,
  unknown
> = z.pipe(
  z.object({
    first_name: types.string(),
    last_name: types.string(),
    timestamp: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "first_name": "firstName",
      "last_name": "lastName",
    });
  }),
);

export function flowkitUserAuditEntryFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitUserAuditEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitUserAuditEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitUserAuditEntry' from JSON`,
  );
}
