/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitUserAuditEntry,
  FlowkitUserAuditEntry$inboundSchema,
} from "./flowkit-user-audit-entry.js";

export type FlowkitUserAudit = {
  created: FlowkitUserAuditEntry;
  updated: FlowkitUserAuditEntry;
};

/** @internal */
export const FlowkitUserAudit$inboundSchema: z.ZodMiniType<
  FlowkitUserAudit,
  unknown
> = z.object({
  created: FlowkitUserAuditEntry$inboundSchema,
  updated: FlowkitUserAuditEntry$inboundSchema,
});

export function flowkitUserAuditFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitUserAudit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitUserAudit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitUserAudit' from JSON`,
  );
}
