/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FlowkitCredentials = {
  /**
   * Base URL for the connected commerce platform.
   */
  url: string;
  /**
   * Integration credential code/token.
   */
  code: string;
};

/** @internal */
export type FlowkitCredentials$Outbound = {
  url: string;
  code: string;
};

/** @internal */
export const FlowkitCredentials$outboundSchema: z.ZodMiniType<
  FlowkitCredentials$Outbound,
  FlowkitCredentials
> = z.object({
  url: z.string(),
  code: z.string(),
});

export function flowkitCredentialsToJSON(
  flowkitCredentials: FlowkitCredentials,
): string {
  return JSON.stringify(
    FlowkitCredentials$outboundSchema.parse(flowkitCredentials),
  );
}
