/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FlowkitParam = {
  key: string;
  description?: string | undefined;
  type: string;
  required: boolean;
};

/** @internal */
export const FlowkitParam$inboundSchema: z.ZodMiniType<FlowkitParam, unknown> =
  z.object({
    key: types.string(),
    description: types.optional(types.string()),
    type: types.string(),
    required: types.boolean(),
  });

export function flowkitParamFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitParam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitParam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitParam' from JSON`,
  );
}
