/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FlowkitConnectorRef = {
  connectorId?: string | undefined;
  connectorSlug?: string | undefined;
};

/** @internal */
export const FlowkitConnectorRef$inboundSchema: z.ZodMiniType<
  FlowkitConnectorRef,
  unknown
> = z.pipe(
  z.object({
    connector_id: types.optional(types.string()),
    connector_slug: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "connector_id": "connectorId",
      "connector_slug": "connectorSlug",
    });
  }),
);

export function flowkitConnectorRefFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitConnectorRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitConnectorRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitConnectorRef' from JSON`,
  );
}
