/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitDefinition,
  FlowkitDefinition$inboundSchema,
} from "./flowkit-definition.js";
import { Meta, Meta$inboundSchema } from "./meta.js";

export type FlowkitListResponseData = {
  data?: Array<FlowkitDefinition> | undefined;
  total?: Meta | undefined;
};

export type FlowkitListResponse = {
  data?: FlowkitListResponseData | undefined;
};

/** @internal */
export const FlowkitListResponseData$inboundSchema: z.ZodMiniType<
  FlowkitListResponseData,
  unknown
> = z.object({
  data: types.optional(z.array(FlowkitDefinition$inboundSchema)),
  total: types.optional(Meta$inboundSchema),
});

export function flowkitListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitListResponseData' from JSON`,
  );
}

/** @internal */
export const FlowkitListResponse$inboundSchema: z.ZodMiniType<
  FlowkitListResponse,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => FlowkitListResponseData$inboundSchema)),
});

export function flowkitListResponseFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitListResponse' from JSON`,
  );
}
