/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AuditEntryByName,
  AuditEntryByName$inboundSchema,
} from "./audit-entry-by-name.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitConnectorRef,
  FlowkitConnectorRef$inboundSchema,
} from "./flowkit-connector-ref.js";
import {
  FlowkitFlowRef,
  FlowkitFlowRef$inboundSchema,
} from "./flowkit-flow-ref.js";
import { FlowkitParam, FlowkitParam$inboundSchema } from "./flowkit-param.js";

export type Audit = {
  /**
   * Audit entry carrying first_name / last_name (list responses).
   */
  updated?: AuditEntryByName | undefined;
};

export type FlowkitDefinition = {
  typename?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  title?: string | undefined;
  revision?: string | undefined;
  description?: string | undefined;
  tenantId?: string | undefined;
  connectors?: Array<FlowkitConnectorRef> | undefined;
  flows?: Array<FlowkitFlowRef> | undefined;
  params?: Array<FlowkitParam> | undefined;
  audit?: Audit | undefined;
};

/** @internal */
export const Audit$inboundSchema: z.ZodMiniType<Audit, unknown> = z.object({
  updated: types.optional(AuditEntryByName$inboundSchema),
});

export function auditFromJSON(
  jsonString: string,
): SafeParseResult<Audit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Audit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Audit' from JSON`,
  );
}

/** @internal */
export const FlowkitDefinition$inboundSchema: z.ZodMiniType<
  FlowkitDefinition,
  unknown
> = z.pipe(
  z.object({
    __typename: types.optional(types.string()),
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    title: types.optional(types.string()),
    revision: types.optional(types.string()),
    description: types.optional(types.string()),
    tenant_id: types.optional(types.string()),
    connectors: types.optional(z.array(FlowkitConnectorRef$inboundSchema)),
    flows: types.optional(z.array(FlowkitFlowRef$inboundSchema)),
    params: types.optional(z.array(FlowkitParam$inboundSchema)),
    audit: types.optional(z.lazy(() => Audit$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "__typename": "typename",
      "tenant_id": "tenantId",
    });
  }),
);

export function flowkitDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<FlowkitDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FlowkitDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FlowkitDefinition' from JSON`,
  );
}
