/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type HealthResponse = {
  status: string;
};

/** @internal */
export const HealthResponse$inboundSchema: z.ZodMiniType<
  HealthResponse,
  unknown
> = z.object({
  status: types.string(),
});

export function healthResponseFromJSON(
  jsonString: string,
): SafeParseResult<HealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthResponse' from JSON`,
  );
}
