/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const GrantType = {
  ClientCredentials: "client_credentials",
} as const;
export type GrantType = ClosedEnum<typeof GrantType>;

export type IssueTokenRequest = {
  grantType: GrantType;
  clientId: string;
  clientSecret: string;
  /**
   * Space-separated list of scopes to request. Must be a subset of the
   *
   * @remarks
   * scopes configured for the tenant. Omit to request all available scopes.
   */
  scope?: string | undefined;
};

/** @internal */
export const GrantType$outboundSchema: z.ZodMiniEnum<typeof GrantType> = z.enum(
  GrantType,
);

/** @internal */
export type IssueTokenRequest$Outbound = {
  grant_type: string;
  client_id: string;
  client_secret: string;
  scope?: string | undefined;
};

/** @internal */
export const IssueTokenRequest$outboundSchema: z.ZodMiniType<
  IssueTokenRequest$Outbound,
  IssueTokenRequest
> = z.pipe(
  z.object({
    grantType: GrantType$outboundSchema,
    clientId: z.string(),
    clientSecret: z.string(),
    scope: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      grantType: "grant_type",
      clientId: "client_id",
      clientSecret: "client_secret",
    });
  }),
);

export function issueTokenRequestToJSON(
  issueTokenRequest: IssueTokenRequest,
): string {
  return JSON.stringify(
    IssueTokenRequest$outboundSchema.parse(issueTokenRequest),
  );
}
