/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Key = {
  kty: string;
  kid: string;
  use: string;
  alg: string;
  n: string;
  e: string;
};

export type JWKSet = {
  keys: Array<Key>;
};

/** @internal */
export const Key$inboundSchema: z.ZodMiniType<Key, unknown> = z.object({
  kty: types.string(),
  kid: types.string(),
  use: types.string(),
  alg: types.string(),
  n: types.string(),
  e: types.string(),
});

export function keyFromJSON(
  jsonString: string,
): SafeParseResult<Key, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Key$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Key' from JSON`,
  );
}

/** @internal */
export const JWKSet$inboundSchema: z.ZodMiniType<JWKSet, unknown> = z.object({
  keys: z.array(z.lazy(() => Key$inboundSchema)),
});

export function jwkSetFromJSON(
  jsonString: string,
): SafeParseResult<JWKSet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JWKSet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JWKSet' from JSON`,
  );
}
