/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FlowkitActivationListEnvelope,
  FlowkitActivationListEnvelope$inboundSchema,
} from "./flowkit-activation-list-envelope.js";

export type ListFlowkitActivationsResponse = {
  data: FlowkitActivationListEnvelope;
};

/** @internal */
export const ListFlowkitActivationsResponse$inboundSchema: z.ZodMiniType<
  ListFlowkitActivationsResponse,
  unknown
> = z.object({
  data: FlowkitActivationListEnvelope$inboundSchema,
});

export function listFlowkitActivationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListFlowkitActivationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFlowkitActivationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFlowkitActivationsResponse' from JSON`,
  );
}
