/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Meta = {
  typename?: string | undefined;
  count?: number | undefined;
};

/** @internal */
export const Meta$inboundSchema: z.ZodMiniType<Meta, unknown> = z.pipe(
  z.object({
    __typename: types.optional(types.string()),
    count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "__typename": "typename",
    });
  }),
);

export function metaFromJSON(
  jsonString: string,
): SafeParseResult<Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Meta' from JSON`,
  );
}
