/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type MetaCount = {
  typename: string;
  count: number;
};

/** @internal */
export const MetaCount$inboundSchema: z.ZodMiniType<MetaCount, unknown> = z
  .pipe(
    z.object({
      __typename: types.string(),
      count: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "__typename": "typename",
      });
    }),
  );

export function metaCountFromJSON(
  jsonString: string,
): SafeParseResult<MetaCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetaCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetaCount' from JSON`,
  );
}
