/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type RefreshRequest = {
  /**
   * Hydra refresh token obtained from `/users/token/exchange` or a prior `/users/token/refresh`
   */
  refreshToken: string;
};

/** @internal */
export type RefreshRequest$Outbound = {
  refresh_token: string;
};

/** @internal */
export const RefreshRequest$outboundSchema: z.ZodMiniType<
  RefreshRequest$Outbound,
  RefreshRequest
> = z.pipe(
  z.object({
    refreshToken: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      refreshToken: "refresh_token",
    });
  }),
);

export function refreshRequestToJSON(refreshRequest: RefreshRequest): string {
  return JSON.stringify(RefreshRequest$outboundSchema.parse(refreshRequest));
}
