/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SchemeBasicAuth = {
  username: string;
  password: string;
};

/** @internal */
export type SchemeBasicAuth$Outbound = {
  username: string;
  password: string;
};

/** @internal */
export const SchemeBasicAuth$outboundSchema: z.ZodMiniType<
  SchemeBasicAuth$Outbound,
  SchemeBasicAuth
> = z.object({
  username: z.string(),
  password: z.string(),
});

export function schemeBasicAuthToJSON(
  schemeBasicAuth: SchemeBasicAuth,
): string {
  return JSON.stringify(SchemeBasicAuth$outboundSchema.parse(schemeBasicAuth));
}
