/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const SessionTokenDataTokenType = {
  Bearer: "bearer",
} as const;
export type SessionTokenDataTokenType = ClosedEnum<
  typeof SessionTokenDataTokenType
>;

export type SessionTokenData = {
  /**
   * Hydra-issued access token
   */
  accessToken: string;
  /**
   * Hydra refresh token; use with `POST /users/token/refresh`
   */
  refreshToken?: string | undefined;
  tokenType: SessionTokenDataTokenType;
  /**
   * Access token lifetime in seconds
   */
  expiresIn: number;
};

/** @internal */
export const SessionTokenDataTokenType$inboundSchema: z.ZodMiniEnum<
  typeof SessionTokenDataTokenType
> = z.enum(SessionTokenDataTokenType);

/** @internal */
export const SessionTokenData$inboundSchema: z.ZodMiniType<
  SessionTokenData,
  unknown
> = z.pipe(
  z.object({
    access_token: types.string(),
    refresh_token: types.optional(types.string()),
    token_type: SessionTokenDataTokenType$inboundSchema,
    expires_in: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "refresh_token": "refreshToken",
      "token_type": "tokenType",
      "expires_in": "expiresIn",
    });
  }),
);

export function sessionTokenDataFromJSON(
  jsonString: string,
): SafeParseResult<SessionTokenData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionTokenData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionTokenData' from JSON`,
  );
}
