/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const TokenType = {
  Bearer: "bearer",
} as const;
export type TokenType = ClosedEnum<typeof TokenType>;

export type TokenData = {
  /**
   * JWT access token
   */
  accessToken: string;
  tokenType: TokenType;
  /**
   * Token lifetime in seconds
   */
  expiresIn: number;
  /**
   * Space-separated list of granted scopes
   */
  scope: string;
};

/** @internal */
export const TokenType$inboundSchema: z.ZodMiniEnum<typeof TokenType> = z.enum(
  TokenType,
);

/** @internal */
export const TokenData$inboundSchema: z.ZodMiniType<TokenData, unknown> = z
  .pipe(
    z.object({
      access_token: types.string(),
      token_type: TokenType$inboundSchema,
      expires_in: types.number(),
      scope: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "access_token": "accessToken",
        "token_type": "tokenType",
        "expires_in": "expiresIn",
      });
    }),
  );

export function tokenDataFromJSON(
  jsonString: string,
): SafeParseResult<TokenData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenData' from JSON`,
  );
}
