/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const TokenDataTokenType = {
  BearerMixed: "Bearer",
  BearerLower: "bearer",
} as const;
export type TokenDataTokenType = OpenEnum<typeof TokenDataTokenType>;

export type TokenData = {
  /**
   * JWT access token
   */
  accessToken: string;
  tokenType: TokenDataTokenType;
  /**
   * Token lifetime in seconds
   */
  expiresIn: number;
  /**
   * Space-separated list of granted scopes
   */
  scope?: string | undefined;
};

/** @internal */
export const TokenDataTokenType$inboundSchema: z.ZodMiniType<
  TokenDataTokenType,
  unknown
> = openEnums.inboundSchema(TokenDataTokenType);

/** @internal */
export const TokenData$inboundSchema: z.ZodMiniType<TokenData, unknown> = z
  .pipe(
    z.object({
      access_token: types.string(),
      token_type: TokenDataTokenType$inboundSchema,
      expires_in: types.number(),
      scope: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "access_token": "accessToken",
        "token_type": "tokenType",
        "expires_in": "expiresIn",
      });
    }),
  );

export function tokenDataFromJSON(
  jsonString: string,
): SafeParseResult<TokenData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenData' from JSON`,
  );
}
