/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const UserTokenDataTokenType = {
  BearerMixed: "Bearer",
  BearerLower: "bearer",
} as const;
export type UserTokenDataTokenType = OpenEnum<typeof UserTokenDataTokenType>;

export type UserTokenData = {
  accessToken: string;
  tokenType: UserTokenDataTokenType;
  /**
   * Effective token lifetime in seconds (always set; capped at server config)
   */
  expiresIn: number;
};

/** @internal */
export const UserTokenDataTokenType$inboundSchema: z.ZodMiniType<
  UserTokenDataTokenType,
  unknown
> = openEnums.inboundSchema(UserTokenDataTokenType);

/** @internal */
export const UserTokenData$inboundSchema: z.ZodMiniType<
  UserTokenData,
  unknown
> = z.pipe(
  z.object({
    access_token: types.string(),
    token_type: UserTokenDataTokenType$inboundSchema,
    expires_in: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "token_type": "tokenType",
      "expires_in": "expiresIn",
    });
  }),
);

export function userTokenDataFromJSON(
  jsonString: string,
): SafeParseResult<UserTokenData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserTokenData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserTokenData' from JSON`,
  );
}
