/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UserTokenRequest = {
  externalId: string;
  customerExternalId?: string | undefined;
  email?: string | undefined;
  givenName?: string | undefined;
  familyName?: string | undefined;
  /**
   * Requested token lifetime in seconds. Capped at `BOOTSTRAP_TOKEN_TTL_SECONDS`
   *
   * @remarks
   * (default: 300s). Values equal to or above the cap use the cap.
   */
  expiresIn?: number | undefined;
};

/** @internal */
export type UserTokenRequest$Outbound = {
  external_id: string;
  customer_external_id?: string | undefined;
  email?: string | undefined;
  given_name?: string | undefined;
  family_name?: string | undefined;
  expires_in?: number | undefined;
};

/** @internal */
export const UserTokenRequest$outboundSchema: z.ZodMiniType<
  UserTokenRequest$Outbound,
  UserTokenRequest
> = z.pipe(
  z.object({
    externalId: z.string(),
    customerExternalId: z.optional(z.string()),
    email: z.optional(z.string()),
    givenName: z.optional(z.string()),
    familyName: z.optional(z.string()),
    expiresIn: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      externalId: "external_id",
      customerExternalId: "customer_external_id",
      givenName: "given_name",
      familyName: "family_name",
      expiresIn: "expires_in",
    });
  }),
);

export function userTokenRequestToJSON(
  userTokenRequest: UserTokenRequest,
): string {
  return JSON.stringify(
    UserTokenRequest$outboundSchema.parse(userTokenRequest),
  );
}
